---
version: "3.8"

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SERVERURL=${SRV_URL}
      - SERVERPORT=${SRV_PORT}
      - PEERS=${PEERS}
      - INTERNAL_SUBNET=${ISUBNET}
      - ALLOWEDIPS=${AIPS}
      - LOG_CONFS=true
    volumes:
      - ./config:/config
      - ./lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: ${RESTART}
